[package]
name = "json-compact"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde_json = { version = "1.0.96", features = ["raw_value"] }
pest = "2.5.7"
pest_derive = "2.5.7"
